# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provname', models.CharField(max_length=140)),
                ('contact', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
