# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('id',), 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
