# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eqmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=140)),
                ('fkbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
    ]
