# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eqmodels', '0001_initial'),
        ('descriptions', '0002_auto_20161006_0051'),
        ('funders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=140, null=True)),
                ('codpat', models.CharField(blank=True, max_length=20, null=True)),
                ('fkdescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.Description')),
                ('fkeqmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqmodels.Eqmodel')),
                ('fkfunder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funders.Funder')),
            ],
        ),
    ]
