# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('conservations', '0001_initial'),
        ('documents', '0001_initial'),
        ('statuses', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asstfather',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkconservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conservations.Conservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkdocument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkprovider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statuses.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='obswarranty',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='references',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='codpat',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(blank=True, default=1, max_length=140),
            preserve_default=False,
        ),
    ]
