# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('conservations', '0001_initial'),
        ('providers', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asstfather',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='datebuy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='fkconservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conservations.Conservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkprovider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='fkstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statuses.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='obswarranty',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='references',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
