# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('assets', '0002_auto_20161006_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('fkasset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('fkfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
            ],
            options={
                'ordering': ('fkasset',),
                'verbose_name': 'Detail Feature',
                'verbose_name_plural': 'Details Features',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='features',
            field=models.ManyToManyField(through='assets.DetailFeature', to='features.Feature'),
        ),
    ]
