# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20161006_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asstfather',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='references',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty',
            field=models.CharField(max_length=50),
        ),
    ]
