# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20161006_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='references',
            new_name='reference',
        ),
    ]
