# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20161006_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='reference',
            new_name='observation',
        ),
    ]
