# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20161006_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='datebuy',
            field=models.DateField(auto_now=True),
        ),
    ]
