# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_datebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='datebuy',
            field=models.DateField(),
        ),
    ]
