# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20161006_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='docnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
