# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_docnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asstfather',
            new_name='assetfather',
        ),
    ]
