# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('typetransfers', '0001_initial'),
        ('assets', '0008_auto_20161006_2214'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('datetransfer', models.DateField()),
                ('last', models.BooleanField()),
                ('formtransfer', models.FileField(blank=True, null=True, upload_to='media/fileTransfers/%Y/%m/%d/')),
                ('fkasset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('fkdepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
                ('fkowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
                ('fktypetransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typetransfers.TypeTransfer')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
    ]
