# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='formtransfer',
            field=models.FileField(blank=True, null=True, upload_to='transfers/%Y/%m/%d/'),
        ),
    ]
